/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liveshow_rtmp_RtmpJni */

#ifndef _Included_com_liveshow_rtmp_RtmpJni
#define _Included_com_liveshow_rtmp_RtmpJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liveshow_rtmp_RtmpJni
 * Method:    init
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_liveshow_rtmp_RtmpJni_init
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_liveshow_rtmp_RtmpJni
 * Method:    sendSpsAndPps
 * Signature: (J[BI[BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_liveshow_rtmp_RtmpJni_sendSpsAndPps
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jlong);

/*
 * Class:     com_liveshow_rtmp_RtmpJni
 * Method:    sendVideoData
 * Signature: (J[BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_liveshow_rtmp_RtmpJni_sendVideoData
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     com_liveshow_rtmp_RtmpJni
 * Method:    sendAacSpec
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_liveshow_rtmp_RtmpJni_sendAacSpec
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liveshow_rtmp_RtmpJni
 * Method:    sendAacData
 * Signature: (J[BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_liveshow_rtmp_RtmpJni_sendAacData
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     com_liveshow_rtmp_RtmpJni
 * Method:    stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_liveshow_rtmp_RtmpJni_stop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
