/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuyt_liveshow_TestJniUtils */

#ifndef _Included_com_liuyt_liveshow_TestJniUtils
#define _Included_com_liuyt_liveshow_TestJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuyt_liveshow_TestJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liuyt_liveshow_TestJniUtils_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
